os:
- linux
dist: bionic
language: python

services:
- docker

env:
  global:
  - VERSION: 0.0.2

stages:
- name: test
- name: print
  if: branch = master


jobs:
  include:
  - stage: test
    name: Run style, unit and integration tests
    script:
    - python scr/file.py
    - python a.py
    - docker build -t img .
  - stage: run
    name: running Docker image
    script:
    - python a.py



