os:
- linux
dist: bionic
language: python

services:
- docker

env:
  global:
  - VERSION: 0.0.2

stages:
- name: test
- name: run


jobs:
  include:
  - stage: test
    name: Run style, unit and integration tests
    script:
    - python scr/file.py
    - python a.py
    - docker build -t img .
  - stage: run
    name: running Docker image
    script:
    - docker run img
    - docker tag img img:${VERSION}
    - docker tag img img:latest
    - docker images



