os:
- linux
dist: bionic
language: python

services:
- docker

env:
  global:
  - VERSION: 0.0.1

stages:
- name: test


jobs:
  include:
  - stage: test
    name: Run style, unit and integration tests
    script:
    - python scr/file.py
    - python a.py


after_success:
- docker build -t img:latest .
- docker run img:latest
- docker tag ${DOCKER_REPO}:latest ${DOCKER_REPO}:${VERSION}
- docker ps -a
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin
- echo PUSHING DOCKER IMAGE
- docker push rohank63/img:latest
