os:
- linux
dist: bionic
language: python

services:
- docker

env:
  global:
  - VERSION: 0.0.2

stages:
- name: test


jobs:
  include:
  - stage: test
    name: Run style, unit and integration tests
    script:
    - python scr/file.py
    - python a.py


after_success:
- export REPO=${DOCKER_USER}/${DOCKER_REPO} 
- docker build -t ${REPO} .
- docker run ${REPO}
- docker tag ${REPO} ${REPO}:${VERSION}
- docker tag ${REPO} ${REPO}:latest
- docker images
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin
- echo PUSHING DOCKER IMAGE
- docker push ${REPO}
