os:
- linux
dist: bionic
language: python

services:
- docker

env:
  global:
  - VERSION: 0.0.2

stages:
- name: test
- name: run


jobs:
  include:
  - stage: test
    name: Run style, unit and integration tests
    script:
    - python scr/file.py
    - python a.py
    - export REPO=${DOCKER_USER}/${DOCKER_REPO} 
    - docker build -t ${REPO} .
  - stage: run
    name: running Docker image
    - docker run ${REPO}
    - docker tag ${REPO} ${REPO}:${VERSION}
    - docker tag ${REPO} ${REPO}:latest
    - docker images



