os:
- linux
dist: bionic
language: python

services:
- docker

env:
  global:
  - VERSION: 0.0.1

stages:
- name: test


jobs:
  include:
  - stage: test
    name: Run style, unit and integration tests
    script:
    - python scr/file.py
    - python a.py


after_success:
- docker build -t img .
- docker run img
- docker tag ${DOCKER_REPO}:latest
- docker tag ${DOCKER_REPO}:${VERSION}
- echo ${DOCKER_PASSWORD} | docker login -u ${$DOCKER_USERNAME} --password-stdin
- echo PUSHING DOCKER IMAGE
- docker push ${DOCKER_USER}/${DOCKER_REPO}:${VERSION}
